### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [worldbeater/Camelotia#21]
Hi @worldbeater I make contributions to open source projects in my spare time by designing logos. For this project I have a functional and minimalist idea in my mind. I'd like to show it to you if you let me. What do you think?

**Comment by worldbeater** [comment]
Hi, @reallinfo! If your are OK with MIT license, then I'm open for suggestions!

By the way, I know folks from the [ReactiveUI organization](https://github.com/reactiveui) are willing to get a logo for their new [Pharmacist](https://github.com/reactiveui/Pharmacist) project which scans .NET assemblies and turns all pub-sub events into [IObservable](http://reactivex.io/)s. The current project logo in [Pharmacist](https://github.com/reactiveui/Pharmacist) `README.md` is actually borrowed from the [Splat](https://github.com/reactiveui/splat) project. Those folks from ReactiveUI could offer contract work as well! If you are interested, then we can continue the conversation on this subject at [ReactiveUI Slack](http://reactiveui.net/slack), `reactiveui-dev` channel.

Thank you for being interested in this project and for all the things you do for open-source!

**Comment by reallinfo** [comment]
Hi again, I choose 3 keywords to represents the function of the project. These; cloud, folder, xamarin. Also, I will deal with the project you mentioned. What do you think about the logo?

![camelotia](https://user-images.githubusercontent.com/36298335/57973854-dc174780-79b7-11e9-95fe-f4842e81565a.jpg)

**Comment by worldbeater** [comment]
Wow, that looks really cool! Instantly fallen in love with the first option :medal_sports:

**Comment by reallinfo** [comment]
Thanks :) can i send a pr. if you want, i can update the readme file. 

![cam](https://user-images.githubusercontent.com/36298335/57974480-6912ce80-79c1-11e9-8f6f-7c5a74bc1dc1.png)

**Comment by worldbeater** [comment]
Yes please, would be happy to accept a PR! Thank you so much! By the way, how about making the logo a bit smaller and aligning it to the left, as other titles and text blocks are aligned on the page?

**Comment by reallinfo** [comment]
Sure! Please check it. https://github.com/worldbeater/Camelotia/pull/24
